{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.common.keys import Keys\n",
    "from selenium.common.exceptions import NoSuchElementException\n",
    "\n",
    "import time\n",
    "import numpy as np\n",
    "import logging\n",
    "\n",
    "import string\n",
    "import random\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 90, in <module>\n",
      "    elem = driver.find_element(\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .edit-address.text-muted\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 113, in <module>\n",
      "    street = driver.find_element(By.ID, \"field-address1\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-address1\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 90, in <module>\n",
      "    elem = driver.find_element(\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .edit-address.text-muted\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 113, in <module>\n",
      "    street = driver.find_element(By.ID, \"field-address1\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-address1\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 62, in <module>\n",
      "    name = driver.find_element(By.ID, \"field-firstname\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"field-firstname\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n",
      "ERROR:root:An exception was thrown!\n",
      "Traceback (most recent call last):\n",
      "  File \"/tmp/ipykernel_40374/2893553073.py\", line 151, in <module>\n",
      "    payment_option = driver.find_element(By.ID, \"payment-option-2\")\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 831, in find_element\n",
      "    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n",
      "    self.error_handler.check_response(response)\n",
      "  File \"/home/pyziol/Documents/Studia/Praca_magisterska/pythonVSCode/python-dashboard-panel-main/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n",
      "    raise exception_class(message, screen, stacktrace)\n",
      "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id=\"payment-option-2\"]\n",
      "Stacktrace:\n",
      "RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\n",
      "WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:182:5\n",
      "NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:394:5\n",
      "element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Set up Selenium driver and navigate to online store\n",
    "# driver = webdriver.Chrome()\n",
    "driver = webdriver.Firefox()\n",
    "\n",
    "# Define mean and standard deviation of order volume and product popularity based on historical data\n",
    "mean_order_volume = 1.7\n",
    "stddev_order_volume = 1\n",
    "mean_product_popularity = 1000\n",
    "stddev_product_popularity = 200\n",
    "\n",
    "# Set up random seed for reproducibility\n",
    "# np.random.seed(123)\n",
    "\n",
    "# Generate popularity scores for each product\n",
    "product_popularities = np.round(np.random.normal(\n",
    "    loc=mean_product_popularity, scale=stddev_product_popularity, size=100)).astype(int)\n",
    "\n",
    "# Generate list of product URLs based on their IDs and popularity scores\n",
    "product_urls = [\"http://localhost/prestashop/index.php?id_product=\" +\n",
    "                str(i) + \"&controller=product\" for i in range(1, 101)]\n",
    "product_probs = product_popularities / np.sum(product_popularities)\n",
    "\n",
    "# Loop through each order volume and modify product quantities\n",
    "n_orders = 1000000\n",
    "order_url = \"http://localhost/prestashop/index.php?controller=order\"\n",
    "\n",
    "for i in range(n_orders):\n",
    "\n",
    "    # Select random products and quantities to add to cart\n",
    "    order_volume = int(np.random.normal(\n",
    "        loc=mean_order_volume, scale=stddev_order_volume))\n",
    "    if order_volume < 1:\n",
    "        order_volume = 1\n",
    "    product_selections = np.random.choice(\n",
    "        product_urls, size=order_volume, replace=True, p=product_probs)\n",
    "    np.random\n",
    "    try:\n",
    "        for product_url in product_selections:\n",
    "            driver.get(product_url)  # navigate to product page\n",
    "            # Modify quantity of product\n",
    "            quantity_field = driver.find_element(By.NAME, \"qty\")\n",
    "            # generate new quantity value\n",
    "            new_quantity = int(np.random.uniform(1, 2))\n",
    "            # quantity_field.send_keys(str(new_quantity))  # input new quantity value\n",
    "            driver.execute_script(\n",
    "                f\"document.getElementById('quantity_wanted').value ={str(new_quantity)}\")\n",
    "\n",
    "            time.sleep(1)\n",
    "\n",
    "            # adding order to cart\n",
    "            button = driver.find_element(\n",
    "                By.CLASS_NAME, \"btn.btn-primary.add-to-cart\")\n",
    "            button.click()\n",
    "            time.sleep(1)\n",
    "\n",
    "        # go to order page\n",
    "        time.sleep(1)\n",
    "        driver.get(order_url)\n",
    "        # personal information form\n",
    "\n",
    "        # name\n",
    "        name = driver.find_element(By.ID, \"field-firstname\")\n",
    "        name.clear()\n",
    "        name.send_keys(''.join(random.choices(string.ascii_uppercase, k=9)))\n",
    "\n",
    "        # surname\n",
    "        surname = driver.find_element(By.ID, \"field-lastname\")\n",
    "        surname.clear()\n",
    "        surname.send_keys(''.join(random.choices(string.ascii_uppercase, k=9)))\n",
    "\n",
    "        # mail\n",
    "        mail = driver.find_element(By.ID, \"field-email\")\n",
    "        mail.clear()\n",
    "        mail.send_keys(f\"{np.random.randint(1000000)}@mail.pl\")\n",
    "\n",
    "        # check first agree\n",
    "        check_box1 = driver.find_element(By.NAME, \"customer_privacy\")\n",
    "        check_box1.click()\n",
    "\n",
    "        # check second agree\n",
    "        check_box2 = driver.find_element(By.NAME, \"psgdpr\")\n",
    "        check_box2.click()\n",
    "\n",
    "        # go to next page\n",
    "        data_confirm = driver.find_element(By.NAME, \"continue\")\n",
    "        data_confirm.click()\n",
    "\n",
    "        # formularz adres\n",
    "        try:\n",
    "            elem = driver.find_element(\n",
    "                By.CLASS_NAME, \"edit-address.text-muted\")\n",
    "            if elem.is_displayed():\n",
    "                elem.click()  # this will click the element if it is there\n",
    "                time.sleep(1)\n",
    "                street = driver.find_element(By.ID, \"field-address1\")\n",
    "                street.clear()\n",
    "                street.send_keys(np.random.randint(1000000))\n",
    "\n",
    "                city = driver.find_element(By.ID, \"field-city\")\n",
    "                city.clear()\n",
    "                city.send_keys(np.random.randint(1000000))\n",
    "\n",
    "                post_code = driver.find_element(By.ID, \"field-postcode\")\n",
    "                post_code.clear()\n",
    "                post_code.send_keys(\n",
    "                    f\"50-{np.random.randint(low= 100,high= 999)}\")\n",
    "\n",
    "                adres_confirm = driver.find_element(\n",
    "                    By.NAME, \"confirm-addresses\")\n",
    "                adres_confirm.click()\n",
    "\n",
    "        except NoSuchElementException:\n",
    "            street = driver.find_element(By.ID, \"field-address1\")\n",
    "            street.clear()\n",
    "            street.send_keys(np.random.randint(1000000))\n",
    "\n",
    "            city = driver.find_element(By.ID, \"field-city\")\n",
    "            city.clear()\n",
    "            city.send_keys(np.random.randint(1000000))\n",
    "\n",
    "            post_code = driver.find_element(By.ID, \"field-postcode\")\n",
    "            post_code.clear()\n",
    "            post_code.send_keys(f\"50-{np.random.randint(low= 100,high= 999)}\")\n",
    "\n",
    "            adres_confirm = driver.find_element(By.NAME, \"confirm-addresses\")\n",
    "            adres_confirm.click()\n",
    "\n",
    "        # driver.find_element(By.CLASS_NAME, \"edit-address.text-muted\")\n",
    "\n",
    "        # street = driver.find_element(By.ID, \"field-address1\")\n",
    "        # street.clear()\n",
    "        # street.send_keys(np.random.randint(1000000))\n",
    "\n",
    "        # city = driver.find_element(By.ID, \"field-city\")\n",
    "        # city.clear()\n",
    "        # city.send_keys(np.random.randint(1000000))\n",
    "\n",
    "        # post_code = driver.find_element(By.ID, \"field-postcode\")\n",
    "        # post_code.clear()\n",
    "        # post_code.send_keys(f\"50-{np.random.randint(low= 100,high= 999)}\")\n",
    "\n",
    "        # adres_confirm = driver.find_element(By.NAME, \"confirm-addresses\")\n",
    "        # adres_confirm.click()\n",
    "\n",
    "        # formularz dostawa\n",
    "        delivery_confirm = driver.find_element(\n",
    "            By.NAME, \"confirmDeliveryOption\")\n",
    "        delivery_confirm.click()\n",
    "\n",
    "        # formularz płatność\n",
    "        payment_option = driver.find_element(By.ID, \"payment-option-2\")\n",
    "        payment_option.click()\n",
    "        last_agree = driver.find_element(\n",
    "            By.ID, \"conditions_to_approve[terms-and-conditions]\")\n",
    "        last_agree.click()\n",
    "        time.sleep(1)\n",
    "        # payment_confirm = driver.find_element(By.NAME, \"confirm-addresses\")\n",
    "        # payment_confirm.click()\n",
    "        make_order = driver.find_element(\n",
    "            By.CLASS_NAME, \"btn.btn-primary.center-block\")\n",
    "        make_order.click()\n",
    "\n",
    "        # Wait for a few seconds before proceeding to the next order\n",
    "        time.sleep(1)\n",
    "\n",
    "    # except Exception as e: print(e)\n",
    "    except BaseException:\n",
    "        logging.exception(\"An exception was thrown!\")\n",
    "\n",
    "\n",
    "# Close Selenium driver\n",
    "driver.quit()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
